[build]
publish = "frontend"
command = ""

[[redirects]]
from = "/overlay/*"
to = "/overlay.html"
status = 200

[[redirects]]
from = "/control/*"
to = "/control.html"
status = 200

[[redirects]]
from = "/*"
to = "/viewer.html"
status = 200
