[build]
publish = "frontend"
command = ""

[[redirects]]
from = "/*"
to = "/overlay.html"
status = 200
conditions = { Host = "overlay.phummylw.com" }

[[redirects]]
from = "/*"
to = "/control.html"
status = 200
conditions = { Host = "control.phummylw.com" }

[[redirects]]
from = "/*"
to = "/viewer.html"
status = 200
